version: '3'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB={$POSTGRES_DB:-node_js}
      - POSTGRES_USER={$POSTGRES_USER:-node_user}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD:-node_user_password}
    networks:
      - frontend
      - backend
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB={$POSTGRES_DB:-node_js}
      - POSTGRES_USER={$POSTGRES_USER:-node_user}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD:-node_user_password}
    networks:
    - backend

networks:
  frontend:
  backend: